// Generated by view binder compiler. Do not edit!
package com.foundation.app.simple.backup;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;

import com.foundation.app.simple.R;

public final class ActVbBindingCopy implements ViewBinding {
    @NonNull
    private final LinearLayout rootView;

    @NonNull
    public final Button btn;

    private ActVbBindingCopy(@NonNull LinearLayout rootView, @NonNull Button btn) {
        this.rootView = rootView;
    this.btn = btn;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActVbBindingCopy inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActVbBindingCopy inflate(@NonNull LayoutInflater inflater, @Nullable ViewGroup parent,
                                         boolean attachToParent) {
    View root = inflater.inflate(R.layout.act_vb, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActVbBindingCopy bind(@NonNull View rootView) {
    System.out.println("ActVbBindingCopy bind baseAF");
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId:
    {
      id = R.id.btn;
      Button btn = rootView.findViewById(id);
      if (btn == null) {
        break missingId;
      }

      return new ActVbBindingCopy((LinearLayout) rootView, btn);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
